# Generated by Django 5.2.10 on 2026-01-20 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('seccion', 'Sección'), ('localizacion', 'Localización'), ('patologia', 'Patología'), ('semiologia', 'Semiología')], max_length=30)),
            ],
            options={
                'ordering': ['kind', 'name'],
                'unique_together': {('name', 'kind')},
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cic', models.CharField(blank=True, max_length=50)),
                ('centro_medico', models.CharField(blank=True, max_length=150)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('grupo_edad', models.CharField(choices=[('adulta', 'Adulta'), ('pediatrica', 'Pediátrica'), ('geriatrica', 'Geriátrica')], default='adulta', max_length=20)),
                ('diagnostico_inicial', models.TextField(blank=True)),
                ('comentarios', models.TextField(blank=True)),
                ('pruebas_imagen', models.JSONField(blank=True, default=list)),
                ('procedimientos', models.JSONField(blank=True, default=list)),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('validado', 'Validado'), ('publicado', 'Publicado')], default='borrador', max_length=20)),
                ('interes_docente', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_created', to=settings.AUTH_USER_MODEL)),
                ('shared_groups', models.ManyToManyField(blank=True, to='auth.group')),
                ('localizaciones', models.ManyToManyField(blank=True, limit_choices_to={'kind': 'localizacion'}, related_name='cases_localizacion', to='cases.tag')),
                ('patologias', models.ManyToManyField(blank=True, limit_choices_to={'kind': 'patologia'}, related_name='cases_patologia', to='cases.tag')),
                ('secciones', models.ManyToManyField(blank=True, limit_choices_to={'kind': 'seccion'}, related_name='cases_seccion', to='cases.tag')),
            ],
            options={
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
