# Generated by Django 5.2.10 on 2026-01-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='case',
            name='tipo',
        ),
        migrations.AddField(
            model_name='case',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='publicado_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='case',
            name='grupo_edad',
            field=models.CharField(choices=[('adulta', 'Adulta'), ('pediatrica', 'Pediátrica')], default='adulta', max_length=20),
        ),
    ]
