# Generated by Django 5.2.10 on 2026-01-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cases', '0002_remove_case_estado_remove_case_tipo_case_publicado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='shared_groups',
            field=models.ManyToManyField(blank=True, related_name='shared_cases', to='auth.group'),
        ),
    ]
