# Generated by Django 5.2.10 on 2026-01-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_case_shared_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='multimedia_file',
            field=models.FileField(blank=True, null=True, upload_to='case_media/'),
        ),
        migrations.AddField(
            model_name='case',
            name='multimedia_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
