# Generated by Django 5.2.10 on 2026-01-25 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_multimedia_file_case_multimedia_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='multimedia_file',
        ),
        migrations.RemoveField(
            model_name='case',
            name='multimedia_url',
        ),
        migrations.CreateModel(
            name='CaseMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='case_media/')),
                ('url', models.URLField(blank=True, null=True)),
                ('caption', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='cases.case')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
