# Generated by Django 5.2.10 on 2026-01-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_remove_case_multimedia_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemedia',
            name='title',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre'),
        ),
    ]
