# Generated by Django 5.2.10 on 2026-02-18 16:55

import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_casemedia_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=cases.models.case_media_path),
        ),
    ]
